/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token for a new token pair */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current access + refresh token pair */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the currently authenticated user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cases visible to the caller (paginated, searchable) */
        get: operations["CasesController_list"];
        put?: never;
        /** Create a case (parent only) */
        post: operations["CasesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a case by id */
        get: operations["CasesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a case (owner only) */
        patch: operations["CasesController_update"];
        trace?: never;
    };
    "/cases/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tutors invited to a case (owner only) */
        get: operations["CasesController_listInvites"];
        put?: never;
        /** Invite a tutor to a case (owner only) */
        post: operations["CasesController_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/invites/{tutorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a tutor's invite (owner only) */
        delete: operations["CasesController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invited tutor and mark the case MATCHED (owner only) */
        post: operations["CasesController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get best-match tutor recommendations for a case (owner only)
         * @description MOCK heuristic recommendation: deterministic, no external LLM. Scores every tutor profile by case-insensitive keyword/subject overlap against the case's subject, level, title, and description; subject matches weigh highest. Returns the top 5, sorted by score with a stable display-name tiebreak.
         */
        get: operations["CasesController_recommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents on a case */
        get: operations["DocumentsController_list"];
        put?: never;
        /** Upload a document to a case */
        post: operations["DocumentsController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a case document (uploader only) */
        delete: operations["DocumentsController_deleteForCase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a document (302 redirect to a 60s presigned URL) */
        get: operations["DocumentsController_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse the tutor directory (parents only) */
        get: operations["TutorProfilesController_listDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the caller's own tutor profile */
        get: operations["TutorProfilesController_getOwn"];
        /** Create or update the caller's own tutor profile */
        put: operations["TutorProfilesController_upsertOwn"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-profiles/me/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a supporting document to the caller's profile */
        post: operations["TutorProfilesController_uploadOwnDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-profiles/me/documents/{docId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a document from the caller's profile */
        delete: operations["TutorProfilesController_deleteOwnDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View a tutor profile (parents: any; tutors: own only) */
        get: operations["TutorProfilesController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-profiles/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a profile's documents (parents: any; tutors: own only) */
        get: operations["TutorProfilesController_listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example tutor@example.com */
            email: string;
            /** @example password123 */
            password: string;
            /** @enum {string} */
            role: "PARENT" | "TUTOR";
            /** @example Jane Doe */
            displayName?: string;
        };
        RegisterResponseDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "PARENT" | "TUTOR";
        };
        LoginDto: {
            /** @example parent@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        TokenResponseDto: {
            accessToken: string;
            /** @description Opaque refresh token; store securely (httpOnly cookie on the FE) */
            refreshToken: string;
            /** @description Access-token lifetime in seconds */
            expiresIn: number;
        };
        RefreshDto: {
            /** @description The opaque refresh token returned by login/refresh */
            refreshToken: string;
        };
        MeResponseDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "PARENT" | "TUTOR";
        };
        CreateCaseDto: {
            /** @example Maths tutor for GCSE */
            title: string;
            /** @example Mathematics */
            subject: string;
            /** @example GCSE */
            level: string;
            /** @example London, UK */
            location: string;
            /**
             * @description Budget per hour in whole currency units
             * @example 40
             */
            budgetPerHour: number;
            /** @example Needs help with algebra and exam technique. */
            description?: string;
        };
        CaseResponseDto: {
            id: string;
            title: string;
            subject: string;
            level: string;
            location: string;
            budgetPerHour: number;
            description?: Record<string, never> | null;
            /** @enum {string} */
            status: "OPEN" | "MATCHED" | "CLOSED";
            ownerId: string;
            /** @description Tutor matched to this case, if any */
            matchedTutorId?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedMetaDto: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        PaginatedCasesDto: {
            data: components["schemas"]["CaseResponseDto"][];
            meta: components["schemas"]["PaginatedMetaDto"];
        };
        UpdateCaseDto: {
            title?: string;
            subject?: string;
            level?: string;
            location?: string;
            budgetPerHour?: number;
            description?: string;
            /** @enum {string} */
            status?: "OPEN" | "MATCHED" | "CLOSED";
        };
        InvitedTutorDto: {
            /** @description Id of the invited tutor (User id) */
            tutorId: string;
            /** @description Tutor display name; falls back to email or empty string */
            displayName: string;
            /** @description Tutor qualifications (empty if no profile yet) */
            qualifications: string[];
        };
        InviteDto: {
            /** @description Id of the tutor to invite */
            tutorId: string;
        };
        AcceptTutorDto: {
            /** @description Id of the invited tutor to accept (matches the case) */
            tutorId: string;
        };
        RecommendationDto: {
            /** @description Id of the recommended tutor (User id) */
            tutorId: string;
            /** @description Tutor display name */
            displayName: string;
            /** @description Tutor qualifications */
            qualifications: string[];
            /** @description Heuristic match score; higher is a better fit */
            score: number;
            /** @description Whether this tutor is already invited to the case */
            alreadyInvited: boolean;
        };
        DocumentResponseDto: {
            id: string;
            originalName: string;
            size: number;
            mime: string;
            caseId: Record<string, never> | null;
            /** @description Id of the user who uploaded the document */
            uploadedById: string;
            /** Format: date-time */
            createdAt: string;
        };
        TutorProfileResponseDto: {
            id: string;
            userId: string;
            displayName: string;
            qualifications: string[];
            experiences: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedProfilesDto: {
            data: components["schemas"]["TutorProfileResponseDto"][];
            meta: Record<string, never>;
        };
        UpsertProfileDto: {
            /** @example Jane Doe */
            displayName: string;
            /**
             * @example [
             *       "BSc Mathematics",
             *       "PGCE"
             *     ]
             */
            qualifications: string[];
            /**
             * @example [
             *       "5 years GCSE tutoring"
             *     ]
             */
            experiences: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many login attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Invalid/expired/reused refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_list: {
        parameters: {
            query?: {
                /** @description Keyword search over the case title */
                q?: string;
                subject?: string;
                level?: string;
                status?: "OPEN" | "MATCHED" | "CLOSED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCasesDto"];
                };
            };
        };
    };
    CasesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponseDto"];
                };
            };
            /** @description Not a parent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponseDto"];
                };
            };
            /** @description Not found or not visible to the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponseDto"];
                };
            };
            /** @description Visible but not owned (e.g. invited tutor) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitedTutorDto"][];
                };
            };
            /** @description Visible but not owned (e.g. invited tutor) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteDto"];
            };
        };
        responses: {
            /** @description Case or tutor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                tutorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case or invite not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptTutorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponseDto"];
                };
            };
            /** @description Tutor is not invited to this case */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Visible but not owned (e.g. invited tutor) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Case already has a different matched tutor */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CasesController_recommendations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationDto"][];
                };
            };
            /** @description Visible but not owned (e.g. invited tutor) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DocumentsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"][];
                };
            };
        };
    };
    DocumentsController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
            /** @description File exceeds 10 MB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unsupported file type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DocumentsController_deleteForCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not the uploader */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DocumentsController_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to a presigned URL */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not visible to the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TutorProfilesController_listDirectory: {
        parameters: {
            query?: {
                /** @description Keyword search over the tutor display name */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProfilesDto"];
                };
            };
            /** @description Not a parent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TutorProfilesController_getOwn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorProfileResponseDto"];
                };
            };
        };
    };
    TutorProfilesController_upsertOwn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorProfileResponseDto"];
                };
            };
        };
    };
    TutorProfilesController_uploadOwnDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    TutorProfilesController_deleteOwnDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TutorProfilesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorProfileResponseDto"];
                };
            };
            /** @description Not found or not visible to the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TutorProfilesController_listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"][];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
